# Use container-based infrastructure
sudo: false

language: scala

scala:
  - 2.11.7
jdk:
  - oraclejdk8

script:
   - sbt ++$TRAVIS_SCALA_VERSION -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M test

before_install:
  - pip install --user codecov
after_success:
  - codecov
